@startuml
ditaa
+--------+   +-------+    +-------+
|        +---+ ditaa +--> |       |
|  Text  |   +-------+    |Diagram|
|Dokument|   |!Magie!|    |       |
|     {d}|   |       |    |       |
+---+----+   +-------+    +-------+
    :                         ^
    |    Ein Haufen Arbeit    |
    +-------------------------+
@enduml
