@startuml Ports and Adapters Architecture
ditaa(-S,-E) 
                             Spring Boot Container + Configuration
                                +-------------------------------------------------------------------------------------------------+
                                |                                                                                                 |
                                |                                                                                                 |
                                |      Adapters                                                                                   | 
                                |      +----------------------------------------------------------------------------------+       |                  
                                |      |                                                                                  |       |
                                |      |                                                                                  |       |
                                |      |                   Application                                                    |       |               
                                |      |                   +--------------------------------------------+                 |       |
                                |      |                   |cPNK                                        |                 |       |
                                |      |                   |                                            |                 |       |
                                |      |                   |          Domain                            |                 |       |                   
+---------------+               | +----+------+       +----+-----+    +-----------------------+    +----+-----+    +------+----+  |              
|Web Client     |---HTTP/REST---->|           +------>|Input Port+--+ |cGRE                   | +--+Input Port|<---+           |  |              
+---------------+               | |           |       +----+-----+  | |                       | |  +----+-----+    |           |  |              
                                | |           |            |        v |                       | |       |          |           |  |
                                | |           |            |      +---+----+                  | v       |          |           |  |             +---------------+
                                | |Web Adapter|            |      |Use Case|             +----+---+     |          |Web Adapter|<---HTTP/REST-->+External System|
                                | |           |            |      +---+----+             |Use case|     |          |           |  |             +---------------+
                                | |           |            |        ^ |     Business Code+----+---+     |          |           |  |              
+---------------+               | |           |       +----+-----+  | |                       |    +----+------+   |           |  |             
|External System|---HTTP/REST---->|           +------>|Input Port+--+ |      (Entities)       | +->|Output Port+-->|           |  |             
+---------------+               | +----+------+       +----+-----+    |                       | |  +----+------+   +------+----+  |             
                                |      |                   |          |                       | |       |                 |       |
                                |      |                   |          |                  +----+-+-+     |                 |       |
                                |      |                   |          |                  |Use case|     |                 |       |                   
                                |      |                   |          |                  +----+---+     |                 |       |                   
                                |      |                   |          |       +--------+      |         |                 |       |                   
                                |      |                   |          +-------+Use case+------+         |                 |       |                   
                                |      |                   |               +--+--------+--+             |                 |       |                   
                                |      |                   |               |              |             |                 |       |                   
                                |      |                   |               v              v             |                 |       |                   
                                |      |                   |        +-----------+   +-----------+       |                 |       |           
                                |      |                   +--------+Output Port+---+Output Port+-------+                 |       |           
                                |      |                            +--+--------+   +------+----+                         |       | 
                                |      |                               |                   |                              |       |                  
                                |      |                               |                   |                              |       |                  
                                |      |                               v                   v                              |       |      
                                |      |                +-------------------+         +-----------+                       |       |
                                |      +----------------+Persistence Adapter+---------+Web Adapter+-----------------------+       |                             
                                |                       +--------+----------+         +-----+-----+                               |
                                |                                |                          |                                     |
                                +--------------------------------|--------------------------|-------------------------------------+
                                                                 |                          |
                                                                 v                          v
                                                        +-----------------+         +---------------+
                                                        |External Database|         |External System|
                                                        +-----------------+         +---------------+

@enduml          
